[INFO    :   django.utils.autoreload] - 2024-01-12 18:43:44,113 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-12 18:44:00,254 : index @ 0016: index get request
[INFO    :             django.server] - 2024-01-12 18:44:00,256 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[INFO    :               app_1.views] - 2024-01-12 18:44:19,762 : contact @ 0023: contact get request
[INFO    :             django.server] - 2024-01-12 18:44:19,765 : log_message @ 0212: "GET /contact/ HTTP/1.1" 200 99
[INFO    :   django.utils.autoreload] - 2024-01-17 18:20:01,611 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-17 18:20:37,569 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-17 18:20:38,208 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-17 18:20:42,954 : index @ 0017: index get request
[INFO    :             django.server] - 2024-01-17 18:20:42,955 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-17 18:20:43,172 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-17 18:20:43,174 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2613
[INFO    :             django.server] - 2024-01-17 18:20:53,869 : log_message @ 0212: "GET /clients HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-17 18:20:53,878 : log_message @ 0212: "GET /clients/ HTTP/1.1" 200 88
[INFO    :   django.utils.autoreload] - 2024-01-17 18:32:07,493 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-17 18:32:08,917 : index @ 0017: index get request
[INFO    :             django.server] - 2024-01-17 18:32:08,919 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[INFO    :             django.server] - 2024-01-17 18:32:14,866 : log_message @ 0212: "GET /clients/ HTTP/1.1" 200 757
[INFO    :   django.utils.autoreload] - 2024-01-19 18:22:31,309 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-19 18:23:22,689 : index @ 0017: index get request
[INFO    :             django.server] - 2024-01-19 18:23:22,690 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-19 18:23:38,927 : log_response @ 0241: Not Found: /orders/5/
[WARNING :             django.server] - 2024-01-19 18:23:38,928 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 404 2808
[INFO    :             django.server] - 2024-01-19 18:25:07,688 : log_message @ 0212: "GET /clients/ HTTP/1.1" 200 757
[INFO    :   django.utils.autoreload] - 2024-01-19 18:29:07,254 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-19 18:30:21,573 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-19 18:30:24,366 : index @ 0017: index get request
[INFO    :             django.server] - 2024-01-19 18:30:24,367 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-19 18:30:36,936 : log_response @ 0241: Not Found: /orders/5/
[WARNING :             django.server] - 2024-01-19 18:30:36,937 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 404 2808
[WARNING :            django.request] - 2024-01-19 18:30:58,700 : log_response @ 0241: Not Found: /orders/3/
[WARNING :             django.server] - 2024-01-19 18:30:58,701 : log_message @ 0212: "GET /orders/3/ HTTP/1.1" 404 2808
[ERROR   :            django.request] - 2024-01-19 18:35:01,252 : log_response @ 0241: Internal Server Error: /orders/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 38, in all_client_orders
    return render(request, 'app_1/all_client_orders.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 196, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
[ERROR   :             django.server] - 2024-01-19 18:35:01,262 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 500 165959
[ERROR   :            django.request] - 2024-01-19 18:36:27,365 : log_response @ 0241: Internal Server Error: /orders/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 38, in all_client_orders
    return render(request, 'app_1/all_client_orders.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 196, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
[ERROR   :             django.server] - 2024-01-19 18:36:27,373 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 500 166111
[ERROR   :            django.request] - 2024-01-19 18:36:32,663 : log_response @ 0241: Internal Server Error: /orders/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 38, in all_client_orders
    return render(request, 'app_1/all_client_orders.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 196, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
[ERROR   :             django.server] - 2024-01-19 18:36:32,670 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 500 166111
[ERROR   :            django.request] - 2024-01-19 18:36:45,727 : log_response @ 0241: Internal Server Error: /orders/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 38, in all_client_orders
    return render(request, 'app_1/all_client_orders.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 196, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
[ERROR   :             django.server] - 2024-01-19 18:36:45,734 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 500 166111
[INFO    :             django.server] - 2024-01-19 18:37:06,830 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 454
[ERROR   :            django.request] - 2024-01-19 18:37:45,521 : log_response @ 0241: Internal Server Error: /orders/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 38, in all_client_orders
    return render(request, 'app_1/all_client_orders.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 241, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\defaulttags.py", line 196, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
[ERROR   :             django.server] - 2024-01-19 18:37:45,529 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 500 166111
[INFO    :             django.server] - 2024-01-19 18:42:16,263 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2139
[INFO    :   django.utils.autoreload] - 2024-01-19 18:43:59,434 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 18:44:47,244 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-19 18:44:53,003 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2361
[INFO    :   django.utils.autoreload] - 2024-01-19 18:47:24,819 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-19 18:47:25,587 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-19 18:47:40,038 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2801
[INFO    :             django.server] - 2024-01-19 18:48:33,519 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2801
[INFO    :             django.server] - 2024-01-19 18:48:35,062 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2836
[INFO    :             django.server] - 2024-01-19 18:49:13,655 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2836
[INFO    :             django.server] - 2024-01-19 18:49:15,083 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2871
[INFO    :             django.server] - 2024-01-19 18:49:43,531 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2871
[INFO    :             django.server] - 2024-01-19 18:49:44,258 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2871
[INFO    :             django.server] - 2024-01-19 18:49:45,432 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2956
[INFO    :             django.server] - 2024-01-19 18:50:13,029 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 2956
[INFO    :             django.server] - 2024-01-19 18:50:14,396 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 3041
[INFO    :             django.server] - 2024-01-19 18:50:27,595 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3037
[INFO    :             django.server] - 2024-01-19 18:51:22,701 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3037
[INFO    :             django.server] - 2024-01-19 18:51:23,974 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3082
[INFO    :             django.server] - 2024-01-19 18:51:38,610 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3082
[INFO    :             django.server] - 2024-01-19 18:51:39,846 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3037
[INFO    :             django.server] - 2024-01-19 18:51:48,871 : log_message @ 0212: "GET /orders/1 HTTP/1.1" 200 3029
[INFO    :             django.server] - 2024-01-19 18:58:25,164 : log_message @ 0212: "GET /orders/2 HTTP/1.1" 200 3029
[INFO    :             django.server] - 2024-01-19 18:58:29,323 : log_message @ 0212: "GET /orders/3 HTTP/1.1" 200 3041
[INFO    :   django.utils.autoreload] - 2024-01-20 17:41:22,130 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-20 17:41:25,711 : index @ 0017: index get request
[INFO    :             django.server] - 2024-01-20 17:41:25,723 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-20 17:41:26,110 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-20 17:41:26,111 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 2814
[INFO    :             django.server] - 2024-01-20 17:41:50,425 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3037
[INFO    :   django.utils.autoreload] - 2024-01-20 17:47:57,496 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 17:47:58,121 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-20 17:52:27,476 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 17:52:28,521 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-20 17:55:45,190 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 17:55:45,949 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 17:55:46,183 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3034
[INFO    :             django.server] - 2024-01-20 17:55:47,163 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 200 3034
[INFO    :   django.utils.autoreload] - 2024-01-20 18:07:58,771 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:07:59,555 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-20 18:20:06,609 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-20 18:20:13,261 : index @ 0018: index get request
[INFO    :             django.server] - 2024-01-20 18:20:13,269 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[ERROR   :            django.request] - 2024-01-20 18:20:22,369 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    sevendays = sorted([product for product in orders.products.all() if orders.date <= date.today() - timedelta(days=7)])
                                               ^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'products'
[ERROR   :             django.server] - 2024-01-20 18:20:22,372 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69104
[INFO    :   django.utils.autoreload] - 2024-01-20 18:22:57,085 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:22:57,826 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:23:00,346 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    sevendays = sorted([order for order.products in orders if order.date <= date.today() - timedelta(days=7)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in <listcomp>
    sevendays = sorted([order for order.products in orders if order.date <= date.today() - timedelta(days=7)])
                                  ^^^^^
NameError: name 'order' is not defined
[ERROR   :             django.server] - 2024-01-20 18:23:00,349 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 72930
[INFO    :   django.utils.autoreload] - 2024-01-20 18:25:50,072 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:25:50,865 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:25:51,295 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    sevendays = sorted([order for order in orders if order.date <= date.today() - timedelta(days=7)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in <listcomp>
    sevendays = sorted([order for order in orders if order.date <= date.today() - timedelta(days=7)])
                                                     ^^^^^^^^^^
AttributeError: 'Order' object has no attribute 'date'
[ERROR   :             django.server] - 2024-01-20 18:25:51,300 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 73223
[INFO    :   django.utils.autoreload] - 2024-01-20 18:26:20,910 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:26:21,609 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:26:21,810 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in <listcomp>
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.date'
[ERROR   :             django.server] - 2024-01-20 18:26:21,814 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 73509
[ERROR   :            django.request] - 2024-01-20 18:27:13,142 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in <listcomp>
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.date'
[ERROR   :             django.server] - 2024-01-20 18:27:13,144 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 73509
[ERROR   :            django.request] - 2024-01-20 18:29:13,512 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in <listcomp>
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'NoneType' and 'datetime.date'
[ERROR   :             django.server] - 2024-01-20 18:29:13,516 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 73509
[INFO    :   django.utils.autoreload] - 2024-01-20 18:30:09,394 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:30:10,041 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:30:10,441 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 46, in order_sort_time
    sevendays = sorted([order for order in orders], key=lambda x: x.date_created)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'
[ERROR   :             django.server] - 2024-01-20 18:30:10,443 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69375
[INFO    :   django.utils.autoreload] - 2024-01-20 18:30:53,711 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:30:54,456 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:30:54,928 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 47, in order_sort_time
    sevendays = sorted([order for order in orders], key=lambda x: x.date_created)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'
[ERROR   :             django.server] - 2024-01-20 18:30:54,931 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69307
[INFO    :   django.utils.autoreload] - 2024-01-20 18:31:35,103 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:31:35,772 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 18:32:04,895 : log_message @ 0212: "GET /products/3 HTTP/1.1" 200 3237
[INFO    :             django.server] - 2024-01-20 18:32:46,734 : log_message @ 0212: "GET /products/3 HTTP/1.1" 200 3275
[INFO    :             django.server] - 2024-01-20 18:33:17,049 : log_message @ 0212: "GET /products/1 HTTP/1.1" 200 3263
[INFO    :             django.server] - 2024-01-20 18:33:23,132 : log_message @ 0212: "GET /products/7 HTTP/1.1" 200 3301
[INFO    :   django.utils.autoreload] - 2024-01-20 18:35:30,325 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 18:35:33,606 : log_message @ 0212: "GET /products/7 HTTP/1.1" 200 3301
[INFO    :             django.server] - 2024-01-20 18:35:40,956 : log_message @ 0212: "GET /products/3 HTTP/1.1" 200 3275
[INFO    :             django.server] - 2024-01-20 18:50:15,872 : log_message @ 0212: "GET /products/3 HTTP/1.1" 200 3302
[INFO    :   django.utils.autoreload] - 2024-01-20 18:51:47,888 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:51:48,586 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:51:50,670 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 46, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Order' and 'Order'
[ERROR   :             django.server] - 2024-01-20 18:51:50,673 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69377
[ERROR   :            django.request] - 2024-01-20 18:54:03,916 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 46, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Order' and 'Order'
[ERROR   :             django.server] - 2024-01-20 18:54:03,918 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69377
[ERROR   :            django.request] - 2024-01-20 18:56:22,546 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 46, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Order' and 'Order'
[ERROR   :             django.server] - 2024-01-20 18:56:22,550 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69377
[INFO    :   django.utils.autoreload] - 2024-01-20 18:56:51,447 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:56:52,362 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-20 18:57:24,033 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 18:57:24,823 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 18:57:26,226 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 46, in order_sort_time
    sevendays = sorted([order for order in orders if date(order.date_created) <= date.today() - timedelta(days=7)])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 46, in <listcomp>
    sevendays = sorted([order for order in orders if date(order.date_created) <= date.today() - timedelta(days=7)])
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'datetime.date' object cannot be interpreted as an integer
[ERROR   :             django.server] - 2024-01-20 18:57:26,230 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 73329
[INFO    :   django.utils.autoreload] - 2024-01-20 19:04:07,429 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:04:08,228 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:04:11,022 : log_message @ 0212: "GET /products/3 HTTP/1.1" 200 3302
[INFO    :   django.utils.autoreload] - 2024-01-20 19:05:28,655 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:05:29,334 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 19:05:30,474 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 49, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Order' and 'Order'
[ERROR   :             django.server] - 2024-01-20 19:05:30,478 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69573
[ERROR   :            django.request] - 2024-01-20 19:09:05,101 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 49, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Order' and 'Order'
[ERROR   :             django.server] - 2024-01-20 19:09:05,104 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69573
[INFO    :   django.utils.autoreload] - 2024-01-20 19:11:23,541 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:11:24,303 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-20 19:11:24,960 : log_response @ 0241: Internal Server Error: /products/3
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 54, in order_sort_time
    sevendays = sorted([order for order in orders if order.date_created <= date.today() - timedelta(days=7)])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'Order' and 'Order'
[ERROR   :             django.server] - 2024-01-20 19:11:24,963 : log_message @ 0212: "GET /products/3 HTTP/1.1" 500 69991
[INFO    :   django.utils.autoreload] - 2024-01-20 19:11:45,622 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:11:46,302 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:11:46,609 : log_message @ 0212: "GET /products/3 HTTP/1.1" 200 3198
[INFO    :             django.server] - 2024-01-20 19:13:23,284 : log_message @ 0212: "GET /products/7 HTTP/1.1" 200 3041
[INFO    :             django.server] - 2024-01-20 19:13:28,322 : log_message @ 0212: "GET /products/1 HTTP/1.1" 200 3186
[INFO    :   django.utils.autoreload] - 2024-01-20 19:21:22,158 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:21:22,950 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:21:29,738 : log_message @ 0212: "GET /products/1/5 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-20 19:21:29,768 : log_message @ 0212: "GET /products/1/5/ HTTP/1.1" 200 3186
[INFO    :   django.utils.autoreload] - 2024-01-20 19:24:25,783 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:24:26,550 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:24:27,153 : log_message @ 0212: "GET /products/1/5/ HTTP/1.1" 200 3134
[INFO    :             django.server] - 2024-01-20 19:25:03,683 : log_message @ 0212: "GET /products/1/59/ HTTP/1.1" 200 3238
[INFO    :             django.server] - 2024-01-20 19:25:12,395 : log_message @ 0212: "GET /products/1/590/ HTTP/1.1" 200 3290
[INFO    :   django.utils.autoreload] - 2024-01-20 19:26:16,253 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:26:16,892 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:26:19,029 : log_message @ 0212: "GET /products/1/590/ HTTP/1.1" 200 3290
[INFO    :             django.server] - 2024-01-20 19:29:01,095 : log_message @ 0212: "GET /products/3/590/ HTTP/1.1" 200 3302
[INFO    :   django.utils.autoreload] - 2024-01-20 19:31:22,757 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:31:23,539 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:31:25,179 : log_message @ 0212: "GET /products/3/590/ HTTP/1.1" 200 3339
[INFO    :             django.server] - 2024-01-20 19:34:22,449 : log_message @ 0212: "GET /products/3/590/ HTTP/1.1" 200 3609
[INFO    :             django.server] - 2024-01-20 19:34:36,395 : log_message @ 0212: "GET /products/3/590/ HTTP/1.1" 200 3609
[INFO    :             django.server] - 2024-01-20 19:34:37,524 : log_message @ 0212: "GET /products/3/590/ HTTP/1.1" 200 3609
[INFO    :             django.server] - 2024-01-20 19:34:43,227 : log_message @ 0212: "GET /products/3/5/ HTTP/1.1" 200 1577
[INFO    :             django.server] - 2024-01-20 19:35:16,125 : log_message @ 0212: "GET /products/3/50/ HTTP/1.1" 200 2931
[INFO    :             django.server] - 2024-01-20 19:36:35,828 : log_message @ 0212: "GET /products/3/50/ HTTP/1.1" 200 2995
[INFO    :   django.utils.autoreload] - 2024-01-20 19:37:39,303 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:37:40,002 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:38:09,702 : log_message @ 0212: "GET /products/3/50/ HTTP/1.1" 200 2781
[INFO    :             django.server] - 2024-01-20 19:38:10,605 : log_message @ 0212: "GET /products/3/50/ HTTP/1.1" 200 2781
[INFO    :   django.utils.autoreload] - 2024-01-20 19:40:07,774 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:40:08,460 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:40:08,641 : log_message @ 0212: "GET /products/3/50/ HTTP/1.1" 200 2781
[INFO    :             django.server] - 2024-01-20 19:40:16,340 : log_message @ 0212: "GET /products/3/500/ HTTP/1.1" 200 3407
[INFO    :             django.server] - 2024-01-20 19:40:23,179 : log_message @ 0212: "GET /products/3/5/ HTTP/1.1" 200 1531
[INFO    :   django.utils.autoreload] - 2024-01-20 19:41:26,044 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:41:26,720 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-20 19:41:31,217 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-20 19:41:31,236 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3034
[INFO    :   django.utils.autoreload] - 2024-01-20 19:42:37,837 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-20 19:42:38,555 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-20 19:42:50,511 : log_response @ 0241: Not Found: /products/1
[WARNING :             django.server] - 2024-01-20 19:42:50,512 : log_message @ 0212: "GET /products/1 HTTP/1.1" 404 3031
[INFO    :             django.server] - 2024-01-20 19:42:56,010 : log_message @ 0212: "GET /products/1/5/ HTTP/1.1" 200 1527
[INFO    :   django.utils.autoreload] - 2024-01-23 13:51:03,608 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-23 13:51:08,098 : index @ 0019: index get request
[INFO    :             django.server] - 2024-01-23 13:51:08,100 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-23 13:51:08,446 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-23 13:51:08,456 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 3034
[INFO    :             django.server] - 2024-01-23 14:40:57,550 : log_message @ 0212: "GET /clients/ HTTP/1.1" 200 757
[INFO    :             django.server] - 2024-01-23 14:41:37,020 : log_message @ 0212: "GET /orders/5 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 14:41:37,050 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3034
[INFO    :             django.server] - 2024-01-23 14:48:08,981 : log_message @ 0212: "GET /products/5/10 HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 14:48:08,994 : log_message @ 0212: "GET /products/5/10/ HTTP/1.1" 200 2153
[INFO    :   django.utils.autoreload] - 2024-01-23 14:50:32,640 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 14:50:33,369 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 14:50:55,370 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3034
[INFO    :   django.utils.autoreload] - 2024-01-23 15:18:12,100 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 15:18:12,942 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 15:18:18,087 : log_response @ 0241: Internal Server Error: /products/5/
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endfor'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 63, in products_from_order
    return render(request, 'app_1/products_from_order.html', context={'order': order})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 14: 'endfor', expected 'endblock'. Did you forget to register or load this tag?
[ERROR   :             django.server] - 2024-01-23 15:18:18,100 : log_message @ 0212: "GET /products/5/ HTTP/1.1" 500 168347
[INFO    :             django.server] - 2024-01-23 15:18:43,239 : log_message @ 0212: "GET /products/5/ HTTP/1.1" 200 629
[INFO    :             django.server] - 2024-01-23 15:19:05,570 : log_message @ 0212: "GET /products/5/ HTTP/1.1" 200 585
[INFO    :             django.server] - 2024-01-23 15:19:33,940 : log_message @ 0212: "GET /products/5/ HTTP/1.1" 200 578
[INFO    :             django.server] - 2024-01-23 15:27:13,890 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3599
[INFO    :             django.server] - 2024-01-23 15:28:22,509 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3624
[INFO    :             django.server] - 2024-01-23 15:28:25,352 : log_message @ 0212: "GET /products/21/ HTTP/1.1" 200 579
[INFO    :             django.server] - 2024-01-23 15:28:33,227 : log_message @ 0212: "GET /products/21/ HTTP/1.1" 200 579
[INFO    :             django.server] - 2024-01-23 15:28:37,683 : log_message @ 0212: "GET /products/22/ HTTP/1.1" 200 580
[INFO    :             django.server] - 2024-01-23 15:28:40,102 : log_message @ 0212: "GET /products/23/ HTTP/1.1" 200 582
[INFO    :             django.server] - 2024-01-23 15:29:02,444 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3644
[INFO    :             django.server] - 2024-01-23 15:29:04,556 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3644
[INFO    :             django.server] - 2024-01-23 15:29:29,642 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3624
[INFO    :             django.server] - 2024-01-23 15:29:30,388 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3624
[INFO    :             django.server] - 2024-01-23 15:30:07,320 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 3584
[INFO    :             django.server] - 2024-01-23 15:30:45,087 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 4109
[INFO    :             django.server] - 2024-01-23 15:30:51,016 : log_message @ 0212: "GET /products/21/ HTTP/1.1" 200 579
[INFO    :             django.server] - 2024-01-23 15:31:45,351 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1112
[INFO    :             django.server] - 2024-01-23 15:32:07,272 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1132
[INFO    :             django.server] - 2024-01-23 15:32:21,520 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1112
[INFO    :             django.server] - 2024-01-23 15:32:23,227 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1112
[INFO    :             django.server] - 2024-01-23 15:32:34,308 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1132
[INFO    :             django.server] - 2024-01-23 15:32:45,031 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1112
[INFO    :             django.server] - 2024-01-23 15:32:52,796 : log_message @ 0212: "GET /orders/5/ HTTP/1.1" 200 1132
[INFO    :             django.server] - 2024-01-23 15:32:56,401 : log_message @ 0212: "GET /products/21/ HTTP/1.1" 200 579
[INFO    :             django.server] - 2024-01-23 15:32:58,193 : log_message @ 0212: "GET /products/21/ HTTP/1.1" 200 579
[INFO    :             django.server] - 2024-01-23 15:33:01,272 : log_message @ 0212: "GET /products/25/ HTTP/1.1" 200 581
[INFO    :             django.server] - 2024-01-23 15:33:40,489 : log_message @ 0212: "GET /products/25/5 HTTP/1.1" 301 0
[ERROR   :            django.request] - 2024-01-23 15:33:40,520 : log_response @ 0241: Internal Server Error: /products/25/5/
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 45, in order_sort_time
    client = Client.objects.get(id=client_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 647, in get
    raise self.model.DoesNotExist(
app_1.models.Client.DoesNotExist: Client matching query does not exist.
[ERROR   :             django.server] - 2024-01-23 15:33:40,523 : log_message @ 0212: "GET /products/25/5/ HTTP/1.1" 500 78263
[INFO    :             django.server] - 2024-01-23 15:34:29,778 : log_message @ 0212: "GET /products/4/5/ HTTP/1.1" 200 1530
[INFO    :             django.server] - 2024-01-23 15:40:28,884 : log_message @ 0212: "GET /products/4/5/ HTTP/1.1" 200 1530
[INFO    :             django.server] - 2024-01-23 15:40:31,645 : log_message @ 0212: "GET /products/5/ HTTP/1.1" 200 578
[INFO    :             django.server] - 2024-01-23 15:40:54,812 : log_message @ 0212: "GET /orders/7/ HTTP/1.1" 200 1132
[INFO    :             django.server] - 2024-01-23 15:40:57,984 : log_message @ 0212: "GET /orders/7/ HTTP/1.1" 200 1132
[INFO    :             django.server] - 2024-01-23 15:41:03,910 : log_message @ 0212: "GET /orders/9/ HTTP/1.1" 200 1132
[INFO    :             django.server] - 2024-01-23 15:41:05,614 : log_message @ 0212: "GET /products/43/ HTTP/1.1" 200 581
[INFO    :             django.server] - 2024-01-23 15:41:08,665 : log_message @ 0212: "GET /products/42/ HTTP/1.1" 200 580
[INFO    :             django.server] - 2024-01-23 15:49:14,150 : log_message @ 0212: "GET /products/4/5/ HTTP/1.1" 200 1786
[INFO    :             django.server] - 2024-01-23 15:49:25,452 : log_message @ 0212: "GET /products/4/500/ HTTP/1.1" 200 4006
[INFO    :             django.server] - 2024-01-23 15:49:53,389 : log_message @ 0212: "GET /products/4/500/ HTTP/1.1" 200 3471
[INFO    :             django.server] - 2024-01-23 15:50:15,530 : log_message @ 0212: "GET /products/4/50/ HTTP/1.1" 200 2837
[INFO    :             django.server] - 2024-01-23 15:50:21,821 : log_message @ 0212: "GET /products/4/5/ HTTP/1.1" 200 1572
[INFO    :             django.server] - 2024-01-23 15:55:45,007 : log_message @ 0212: "GET /products/4/50/ HTTP/1.1" 200 2837
[INFO    :             django.server] - 2024-01-23 15:55:52,633 : log_message @ 0212: "GET /products/45/ HTTP/1.1" 200 577
[INFO    :   django.utils.autoreload] - 2024-01-23 17:09:36,453 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-23 17:09:39,411 : index @ 0020: index get request
[INFO    :             django.server] - 2024-01-23 17:09:39,412 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-23 17:10:04,244 : log_response @ 0241: Not Found: /upproduct/100
[WARNING :             django.server] - 2024-01-23 17:10:04,245 : log_message @ 0212: "GET /upproduct/100 HTTP/1.1" 404 3447
[ERROR   :            django.request] - 2024-01-23 17:10:40,483 : log_response @ 0241: Internal Server Error: /productup/100
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 89, in update_product
    return render(request, 'app_1/update_product.html', {'form': form, 'message': message})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\loader_tags.py", line 294, in do_extends
    parent_name = parser.compile_filter(bits[1])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '/base.html' from 'app_1/base.html'
[ERROR   :             django.server] - 2024-01-23 17:10:40,491 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 500 147242
[INFO    :             django.server] - 2024-01-23 17:11:17,667 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 1064
[INFO    :             django.server] - 2024-01-23 17:11:52,187 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 1096
[INFO    :   django.utils.autoreload] - 2024-01-23 17:16:00,229 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:16:01,125 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:16:03,155 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 1201
[INFO    :   django.utils.autoreload] - 2024-01-23 17:20:31,047 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\forms.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:20:31,797 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:20:32,192 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 24951
[INFO    :   django.utils.autoreload] - 2024-01-23 17:22:21,569 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\forms.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:22:22,301 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:22:23,183 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 24951
[INFO    :             django.server] - 2024-01-23 17:22:24,311 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 24951
[INFO    :   django.utils.autoreload] - 2024-01-23 17:22:32,220 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\forms.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:22:32,904 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:22:33,102 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 1203
[INFO    :   django.utils.autoreload] - 2024-01-23 17:22:46,163 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\forms.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:22:46,863 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:22:47,219 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 200 24951
[INFO    :   django.utils.autoreload] - 2024-01-23 17:24:49,934 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:24:50,932 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 17:25:12,692 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:25:13,616 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 17:27:00,414 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:27:01,193 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 17:28:11,194 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\urls.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:28:12,035 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[WARNING :            django.request] - 2024-01-23 17:28:12,438 : log_response @ 0241: Not Found: /productup/100
[WARNING :             django.server] - 2024-01-23 17:28:12,440 : log_message @ 0212: "GET /productup/100 HTTP/1.1" 404 3425
[ERROR   :            django.request] - 2024-01-23 17:28:16,923 : log_response @ 0241: Internal Server Error: /productup/
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: update_product() missing 1 required positional argument: 'product_id'
[ERROR   :             django.server] - 2024-01-23 17:28:16,926 : log_message @ 0212: "GET /productup/ HTTP/1.1" 500 64583
[INFO    :   django.utils.autoreload] - 2024-01-23 17:28:45,403 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:28:46,070 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 17:28:49,361 : log_message @ 0212: "GET /productup/ HTTP/1.1" 200 24965
[ERROR   :            django.request] - 2024-01-23 17:29:43,126 : log_response @ 0241: Internal Server Error: /productup/
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2112, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Product'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 73, in update_product
    product = Product.objects.get(id=form.cleaned_data['product_'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1548, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1378, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\lookups.py", line 362, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\lookups.py", line 88, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2114, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Product: product426067   price: $477.00>.
[ERROR   :             django.server] - 2024-01-23 17:29:43,136 : log_message @ 0212: "POST /productup/ HTTP/1.1" 500 142039
[INFO    :   django.utils.autoreload] - 2024-01-23 17:31:29,186 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:31:29,889 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-23 17:31:35,589 : update_product @ 0080: Update product426067
[INFO    :             django.server] - 2024-01-23 17:31:35,670 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 24984
[INFO    :   django.utils.autoreload] - 2024-01-23 17:33:51,054 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:33:51,757 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[ERROR   :            django.request] - 2024-01-23 17:33:58,768 : log_response @ 0241: Internal Server Error: /productup/
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 73, in update_product
    product = Product.objects.get(form.cleaned_data['product_'])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1602, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1634, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1481, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
TypeError: cannot unpack non-iterable Product object
[ERROR   :             django.server] - 2024-01-23 17:33:58,777 : log_message @ 0212: "POST /productup/ HTTP/1.1" 500 112701
[INFO    :   django.utils.autoreload] - 2024-01-23 17:35:17,809 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:35:18,535 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-23 17:35:25,608 : update_product @ 0080: Update Laptop
[INFO    :             django.server] - 2024-01-23 17:35:25,663 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 24983
[INFO    :               app_1.views] - 2024-01-23 17:35:30,394 : update_product @ 0080: Update Laptop
[INFO    :             django.server] - 2024-01-23 17:35:30,433 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 24983
[INFO    :               app_1.views] - 2024-01-23 17:35:33,393 : update_product @ 0080: Update Laptop
[INFO    :             django.server] - 2024-01-23 17:35:33,425 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 24983
[INFO    :               app_1.views] - 2024-01-23 17:38:53,586 : update_product @ 0080: Update Laptop
[ERROR   :            django.request] - 2024-01-23 17:38:59,304 : log_response @ 0241: Internal Server Error: /productup/
Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py", line 87, in update_product
    product.save()
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\base.py", line 1036, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\base.py", line 1101, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\query.py", line 1276, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1990, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Vadim\Desktop\DjangoHomework\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: database is locked
[ERROR   :             django.server] - 2024-01-23 17:38:59,314 : log_message @ 0212: "POST /productup/ HTTP/1.1" 500 154183
[INFO    :             django.server] - 2024-01-23 17:39:21,430 : log_message @ 0212: "GET /productup/ HTTP/1.1" 200 24958
[INFO    :               app_1.views] - 2024-01-23 17:39:54,223 : update_product @ 0080: Update product764893
[INFO    :             django.server] - 2024-01-23 17:39:54,270 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 24971
[INFO    :   django.utils.autoreload] - 2024-01-23 17:56:28,142 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 17:56:29,067 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 18:08:25,270 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 18:08:33,649 : log_message @ 0212: "GET /productup/ HTTP/1.1" 200 25118
[INFO    :             django.server] - 2024-01-23 18:09:26,015 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 25264
[INFO    :             django.server] - 2024-01-23 18:09:46,664 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 25276
[INFO    :               app_1.views] - 2024-01-23 18:10:10,682 : update_product @ 0081: Update product616775
[INFO    :             django.server] - 2024-01-23 18:10:10,728 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 25130
[INFO    :   django.utils.autoreload] - 2024-01-23 18:19:52,754 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:19:53,559 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-23 18:20:04,059 : update_product @ 0082: Update Vadim
[INFO    :             django.server] - 2024-01-23 18:20:04,119 : log_message @ 0212: "POST /productup/ HTTP/1.1" 200 25130
[INFO    :   django.utils.autoreload] - 2024-01-23 18:32:32,922 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\forms.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:32:33,890 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-23 18:37:20,283 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\views.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-23 18:37:21,047 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-23 18:37:26,410 : log_message @ 0212: "GET /productcreat HTTP/1.1" 301 0
[INFO    :             django.server] - 2024-01-23 18:37:26,433 : log_message @ 0212: "GET /productcreat/ HTTP/1.1" 200 1397
[INFO    :               app_1.views] - 2024-01-23 18:38:00,441 : create_product @ 0117: Create name='Kidav21'
[INFO    :             django.server] - 2024-01-23 18:38:00,479 : log_message @ 0212: "POST /productcreat/ HTTP/1.1" 200 1430
[INFO    :             django.server] - 2024-01-23 18:38:44,176 : log_message @ 0212: "GET /productcreat/ HTTP/1.1" 200 1397
[INFO    :   django.utils.autoreload] - 2024-01-29 15:00:49,551 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :               app_1.views] - 2024-01-29 15:00:52,958 : index @ 0021: index get request
[INFO    :             django.server] - 2024-01-29 15:00:52,959 : log_message @ 0212: "GET / HTTP/1.1" 200 254
[WARNING :            django.request] - 2024-01-29 15:00:53,231 : log_response @ 0241: Not Found: /favicon.ico
[WARNING :             django.server] - 2024-01-29 15:00:53,246 : log_message @ 0212: "GET /favicon.ico HTTP/1.1" 404 3602
[INFO    :             django.server] - 2024-01-29 15:00:59,722 : log_message @ 0212: "GET /admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-29 15:00:59,778 : log_message @ 0212: "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
[INFO    :             django.server] - 2024-01-29 15:00:59,816 : log_message @ 0212: "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:00:59,817 : log_message @ 0212: "GET /static/admin/css/base.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:00:59,822 : log_message @ 0212: "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:00:59,828 : log_message @ 0212: "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:00:59,837 : log_message @ 0212: "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:00:59,840 : log_message @ 0212: "GET /static/admin/css/login.css HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:00:59,852 : log_message @ 0212: "GET /static/admin/js/theme.js HTTP/1.1" 304 0
[INFO    :             django.server] - 2024-01-29 15:01:02,791 : log_message @ 0212: "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4319
[INFO    :   django.utils.autoreload] - 2024-01-29 15:02:55,561 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\djangoHW\settings.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 15:02:56,351 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 15:05:42,268 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 15:05:47,686 : log_message @ 0212: "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-29 15:05:47,734 : log_message @ 0212: "GET /admin/ HTTP/1.1" 200 5944
[INFO    :             django.server] - 2024-01-29 15:05:47,887 : log_message @ 0212: "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
[INFO    :             django.server] - 2024-01-29 15:05:47,900 : log_message @ 0212: "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[INFO    :             django.server] - 2024-01-29 15:05:47,905 : log_message @ 0212: "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[INFO    :             django.server] - 2024-01-29 15:07:06,290 : log_message @ 0212: "GET /admin/auth/user/add/ HTTP/1.1" 200 11238
[INFO    :             django.server] - 2024-01-29 15:07:06,343 : log_message @ 0212: "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
[INFO    :             django.server] - 2024-01-29 15:07:06,352 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:07:06,379 : log_message @ 0212: "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
[INFO    :             django.server] - 2024-01-29 15:07:06,382 : log_message @ 0212: "GET /static/admin/js/actions.js HTTP/1.1" 200 8067
[INFO    :             django.server] - 2024-01-29 15:07:06,401 : log_message @ 0212: "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
[INFO    :             django.server] - 2024-01-29 15:07:06,416 : log_message @ 0212: "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[INFO    :             django.server] - 2024-01-29 15:07:06,426 : log_message @ 0212: "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
[INFO    :             django.server] - 2024-01-29 15:07:06,472 : log_message @ 0212: "GET /static/admin/js/core.js HTTP/1.1" 200 6208
[INFO    :             django.server] - 2024-01-29 15:07:06,473 : log_message @ 0212: "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
[INFO    :             django.server] - 2024-01-29 15:07:06,513 : log_message @ 0212: "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[INFO    :             django.server] - 2024-01-29 15:07:06,525 : log_message @ 0212: "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
[INFO    :             django.server] - 2024-01-29 15:07:06,534 : log_message @ 0212: "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
[INFO    :             django.server] - 2024-01-29 15:07:06,563 : log_message @ 0212: "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[INFO    :             django.server] - 2024-01-29 15:07:56,512 : log_message @ 0212: "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-29 15:07:56,566 : log_message @ 0212: "GET /admin/auth/user/2/change/ HTTP/1.1" 200 23743
[INFO    :             django.server] - 2024-01-29 15:07:56,641 : log_message @ 0212: "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15492
[INFO    :             django.server] - 2024-01-29 15:07:56,643 : log_message @ 0212: "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
[INFO    :             django.server] - 2024-01-29 15:07:56,644 : log_message @ 0212: "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
[INFO    :             django.server] - 2024-01-29 15:07:56,645 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:07:56,645 : log_message @ 0212: "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
[INFO    :             django.server] - 2024-01-29 15:07:56,708 : log_message @ 0212: "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[INFO    :             django.server] - 2024-01-29 15:07:56,784 : log_message @ 0212: "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[INFO    :             django.server] - 2024-01-29 15:07:56,785 : log_message @ 0212: "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[INFO    :             django.server] - 2024-01-29 15:07:56,786 : log_message @ 0212: "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[INFO    :             django.server] - 2024-01-29 15:07:56,791 : log_message @ 0212: "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[INFO    :             django.server] - 2024-01-29 15:07:56,791 : log_message @ 0212: "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[INFO    :             django.server] - 2024-01-29 15:07:56,791 : log_message @ 0212: "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[INFO    :             django.server] - 2024-01-29 15:08:47,878 : log_message @ 0212: "POST /admin/auth/user/2/change/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-29 15:08:47,915 : log_message @ 0212: "GET /admin/auth/user/ HTTP/1.1" 200 12642
[INFO    :             django.server] - 2024-01-29 15:08:47,960 : log_message @ 0212: "GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
[INFO    :             django.server] - 2024-01-29 15:08:47,962 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:08:47,995 : log_message @ 0212: "GET /static/admin/js/filters.js HTTP/1.1" 200 978
[INFO    :             django.server] - 2024-01-29 15:08:48,035 : log_message @ 0212: "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
[INFO    :             django.server] - 2024-01-29 15:08:48,035 : log_message @ 0212: "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[INFO    :             django.server] - 2024-01-29 15:08:48,035 : log_message @ 0212: "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[INFO    :             django.server] - 2024-01-29 15:12:47,020 : log_message @ 0212: "GET /admin/auth/user/1/change/ HTTP/1.1" 200 23483
[INFO    :             django.server] - 2024-01-29 15:12:47,079 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 15:36:38,909 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 15:36:39,794 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 15:36:42,592 : log_message @ 0212: "GET /admin/ HTTP/1.1" 200 8269
[INFO    :             django.server] - 2024-01-29 15:36:46,550 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 15962
[INFO    :             django.server] - 2024-01-29 15:36:46,589 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:36:53,816 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 35698
[INFO    :             django.server] - 2024-01-29 15:36:53,844 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:36:56,932 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 47898
[INFO    :             django.server] - 2024-01-29 15:36:56,963 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:37:18,428 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 15962
[INFO    :             django.server] - 2024-01-29 15:37:18,468 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 15:39:42,538 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\models.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 15:39:43,359 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 15:39:44,577 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 14584
[INFO    :             django.server] - 2024-01-29 15:39:44,630 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:39:55,543 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 38968
[INFO    :             django.server] - 2024-01-29 15:39:55,572 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:40:03,574 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 47898
[INFO    :             django.server] - 2024-01-29 15:40:03,607 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:49:08,804 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 47898
[INFO    :             django.server] - 2024-01-29 15:49:08,850 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:49:09,975 : log_message @ 0212: "GET /admin/app_1/product/add/ HTTP/1.1" 200 12663
[INFO    :             django.server] - 2024-01-29 15:49:10,008 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:49:29,281 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 38968
[INFO    :             django.server] - 2024-01-29 15:49:29,316 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:49:33,807 : log_message @ 0212: "GET /admin/app_1/order/add/ HTTP/1.1" 200 37504
[INFO    :             django.server] - 2024-01-29 15:49:33,841 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:57:16,927 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 47898
[INFO    :             django.server] - 2024-01-29 15:57:17,004 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:57:18,449 : log_message @ 0212: "GET /admin/app_1/product/378/change/ HTTP/1.1" 200 13329
[INFO    :             django.server] - 2024-01-29 15:57:18,492 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:59:12,231 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 47898
[INFO    :             django.server] - 2024-01-29 15:59:12,282 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:59:38,346 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 14584
[INFO    :             django.server] - 2024-01-29 15:59:38,392 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 15:59:40,029 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 38968
[INFO    :             django.server] - 2024-01-29 15:59:40,066 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:04:40,005 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:04:40,874 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:05:25,187 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:07:01,330 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:07:02,079 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:07:02,701 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 52785
[INFO    :             django.server] - 2024-01-29 16:07:05,999 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 52785
[INFO    :             django.server] - 2024-01-29 16:07:06,061 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:07:11,271 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16069
[INFO    :             django.server] - 2024-01-29 16:07:11,303 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:07:16,719 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 52785
[INFO    :             django.server] - 2024-01-29 16:07:16,750 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:07:18,709 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 45454
[INFO    :             django.server] - 2024-01-29 16:07:18,745 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:07:24,619 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16069
[INFO    :             django.server] - 2024-01-29 16:07:24,650 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:07:27,096 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 45454
[INFO    :             django.server] - 2024-01-29 16:07:27,124 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:07:57,482 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:07:58,240 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:08:01,053 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16597
[INFO    :             django.server] - 2024-01-29 16:08:01,106 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:08:04,762 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 45454
[INFO    :             django.server] - 2024-01-29 16:08:04,792 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:08:26,278 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:08:27,053 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:08:28,074 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 47662
[INFO    :             django.server] - 2024-01-29 16:08:28,104 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:08:39,223 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:08:39,913 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:08:40,278 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 52785
[INFO    :             django.server] - 2024-01-29 16:08:40,317 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:08:43,248 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 47677
[INFO    :             django.server] - 2024-01-29 16:08:43,279 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:15:18,128 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16069
[INFO    :             django.server] - 2024-01-29 16:15:18,179 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:15:26,613 : log_message @ 0212: "GET /admin/app_1/client/?o=1 HTTP/1.1" 200 16789
[INFO    :             django.server] - 2024-01-29 16:15:26,650 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:16:10,438 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:16:11,303 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:16:13,838 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 47677
[INFO    :             django.server] - 2024-01-29 16:16:13,874 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:16:26,855 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 53022
[INFO    :             django.server] - 2024-01-29 16:16:26,892 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:16:42,668 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:16:43,412 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:16:43,830 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 52983
[INFO    :             django.server] - 2024-01-29 16:16:43,870 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:17:24,249 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:17:25,037 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:17:25,554 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 53469
[INFO    :             django.server] - 2024-01-29 16:17:25,602 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:17:41,819 : log_message @ 0212: "GET /admin/app_1/product/?o=2.3 HTTP/1.1" 200 56323
[INFO    :             django.server] - 2024-01-29 16:17:41,871 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:18:21,438 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:18:22,189 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:18:23,080 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 48467
[INFO    :             django.server] - 2024-01-29 16:18:23,122 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:24:59,730 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:25:00,506 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:25:07,025 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 54261
[INFO    :             django.server] - 2024-01-29 16:25:07,060 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:25:14,752 : log_message @ 0212: "GET /admin/app_1/order/?date_created__gte=2024-01-22&date_created__lt=2024-01-30 HTTP/1.1" 200 19947
[INFO    :             django.server] - 2024-01-29 16:25:14,792 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:25:17,166 : log_message @ 0212: "GET /admin/app_1/order/? HTTP/1.1" 200 54261
[INFO    :             django.server] - 2024-01-29 16:25:17,203 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:25:18,711 : log_message @ 0212: "GET /admin/app_1/order/?date_created__gte=2024-01-01&date_created__lt=2024-02-01 HTTP/1.1" 200 60184
[INFO    :             django.server] - 2024-01-29 16:25:18,745 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:28:08,309 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:28:09,048 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:28:09,592 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 54261
[INFO    :             django.server] - 2024-01-29 16:28:09,635 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:28:10,839 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 53989
[INFO    :             django.server] - 2024-01-29 16:28:10,873 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:29:50,736 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:29:51,578 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:29:52,183 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16547
[INFO    :             django.server] - 2024-01-29 16:29:52,246 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:29:56,005 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16547
[INFO    :             django.server] - 2024-01-29 16:29:56,041 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:29:59,788 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 54741
[INFO    :             django.server] - 2024-01-29 16:29:59,817 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:30:02,045 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 53990
[INFO    :             django.server] - 2024-01-29 16:30:02,090 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:35:46,302 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:35:47,078 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:35:48,893 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 54741
[INFO    :             django.server] - 2024-01-29 16:35:48,936 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:35:51,873 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 53990
[INFO    :             django.server] - 2024-01-29 16:35:51,942 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:35:56,377 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 53990
[INFO    :             django.server] - 2024-01-29 16:35:56,411 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:36:30,889 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:36:31,622 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:36:33,744 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 54083
[INFO    :             django.server] - 2024-01-29 16:36:33,788 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:36:48,379 : log_message @ 0212: "POST /admin/app_1/product/ HTTP/1.1" 302 0
[INFO    :             django.server] - 2024-01-29 16:36:48,444 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 54083
[INFO    :             django.server] - 2024-01-29 16:36:48,479 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:38:32,717 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:38:33,392 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:39:15,845 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:39:16,452 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:39:23,326 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:39:24,146 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:39:47,747 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:39:48,418 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:41:32,189 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:41:32,865 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:41:33,238 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 54083
[INFO    :             django.server] - 2024-01-29 16:41:33,299 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:41:38,168 : log_message @ 0212: "GET /admin/app_1/product/98/change/ HTTP/1.1" 200 11580
[INFO    :             django.server] - 2024-01-29 16:41:38,202 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:41:58,959 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:41:59,681 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:42:00,096 : log_message @ 0212: "GET /admin/app_1/product/98/change/ HTTP/1.1" 200 12131
[INFO    :             django.server] - 2024-01-29 16:42:00,157 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:42:59,610 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 54741
[INFO    :             django.server] - 2024-01-29 16:42:59,661 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:43:12,124 : log_message @ 0212: "GET /admin/app_1/order/?_facets=True HTTP/1.1" 200 59220
[INFO    :             django.server] - 2024-01-29 16:43:12,164 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:43:12,320 : log_message @ 0212: "GET /static/admin/img/icon-hidelink.svg HTTP/1.1" 200 784
[INFO    :   django.utils.autoreload] - 2024-01-29 16:45:55,039 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:45:55,858 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :   django.utils.autoreload] - 2024-01-29 16:49:03,712 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:49:04,528 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:49:07,096 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 54083
[INFO    :             django.server] - 2024-01-29 16:49:07,134 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:49:08,773 : log_message @ 0212: "GET /admin/app_1/product/98/change/ HTTP/1.1" 200 13265
[INFO    :             django.server] - 2024-01-29 16:49:08,819 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:49:08,944 : log_message @ 0212: "GET /static/admin/js/collapse.js HTTP/1.1" 200 1803
[INFO    :   django.utils.autoreload] - 2024-01-29 16:49:51,931 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:49:52,589 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:49:54,008 : log_message @ 0212: "GET /admin/app_1/product/98/change/ HTTP/1.1" 200 13265
[INFO    :             django.server] - 2024-01-29 16:49:54,059 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:50:09,415 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:50:10,161 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:50:11,374 : log_message @ 0212: "GET /admin/app_1/product/98/change/ HTTP/1.1" 200 13492
[INFO    :             django.server] - 2024-01-29 16:50:11,413 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :   django.utils.autoreload] - 2024-01-29 16:50:56,992 : trigger_reload @ 0266: C:\Users\Vadim\Desktop\DjangoHomework\djangoHW\app_1\admin.py changed, reloading.
[INFO    :   django.utils.autoreload] - 2024-01-29 16:50:57,739 : run_with_reloader @ 0668: Watching for file changes with StatReloader
[INFO    :             django.server] - 2024-01-29 16:50:58,070 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16547
[INFO    :             django.server] - 2024-01-29 16:50:58,126 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:51:00,653 : log_message @ 0212: "GET /admin/app_1/client/ HTTP/1.1" 200 16547
[INFO    :             django.server] - 2024-01-29 16:51:00,694 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:51:02,639 : log_message @ 0212: "GET /admin/app_1/order/ HTTP/1.1" 200 54741
[INFO    :             django.server] - 2024-01-29 16:51:02,673 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:51:04,671 : log_message @ 0212: "GET /admin/app_1/product/ HTTP/1.1" 200 54083
[INFO    :             django.server] - 2024-01-29 16:51:04,707 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
[INFO    :             django.server] - 2024-01-29 16:51:06,652 : log_message @ 0212: "GET /admin/app_1/product/98/change/ HTTP/1.1" 200 13265
[INFO    :             django.server] - 2024-01-29 16:51:06,695 : log_message @ 0212: "GET /admin/jsi18n/ HTTP/1.1" 200 17546
